pages:
- {Home: index.md}
- {About: about.md}
- Series:
  - {Home: index.md}
  - ? !!binary |
      ZGFpbHkgtdrSu8aqvs3Kx8v5zr21xMvpy+nE7g==
    : !!binary |
      ZGFpbHkvtdrSu8aqvs3Kx8v5zr21xMvpy+nE7i5tZA==
site_name: MkLorum
theme: material
